stages:
  - build
  - release


variables:
    PIP_ROOT_USER_ACTION: ignore  # Ignore pip warning when running as root.


default:
    interruptible: true
    
    before_script:
      - apk add --no-cache git
      - pip install --no-cache-dir pdm
      - pdm install --plugins



# 
# Jobs.
#---------------------------------------------------------------------------------------------------
package:
    stage: build
    
    image: python:3.11-alpine3.18
    
    script:
      - pdm build
    
    artifacts:
        paths:
          - .staging/dist/


pages:
    stage: release
    
    image: alpine:3.18.4
    
    variables:
        pages: .staging/pages
    
    script:
      - mkdir -p ${pages}/documentation/
      - cp doc/homepage/* ${pages}/
      - cp doc/documentation/* ${pages}/documentation/
    
    publish: .staging/pages # No trailing slash.
    
    artifacts:
        paths:
          - ${pages}
    
    rules:
      - if: $CI_COMMIT_TAG