stages:
  - build
  - test
  - release


variables:
    PIP_ROOT_USER_ACTION: ignore  # Ignore pip warning when running as root.


default:
    image: python:3.11.6-alpine3.18
    
    interruptible: true
    
    before_script:
      - apk add --no-cache git
      - pip install --no-cache-dir pdm
      - pdm install --plugins



# 
# Jobs.
#---------------------------------------------------------------------------------------------------
package:
    stage: build
    
    script:
      - pdm build
    
    artifacts:
        paths:
          - .staging/dist/


test:
    stage: test
    
    script:
      - pdm sync
      - pdm test
    
    coverage: /^TOTAL.+?(\d+(?:\.\d+)?\%)$/
    
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: .staging/coverage.xml


release:
    stage: release
    
    image: registry.gitlab.com/gitlab-org/release-cli:latest
    
    before_script: []
    
    script:
      - echo Creating new release...
    
    release:
        tag_name: ${CI_COMMIT_TAG}
        description: ${CI_COMMIT_TAG}   
    
    rules:
      - if: $CI_COMMIT_TAG


pages:
    stage: release
    
    variables:
        pages: .staging/pages
    
    script:
      - mkdir -p ${pages}/documentation/
      - cp doc/homepage/* ${pages}/
      - cp doc/documentation/* ${pages}/documentation/
    
    publish: .staging/pages # No trailing slash.
    
    artifacts:
        paths:
          - ${pages}
    
    rules:
      - if: $CI_COMMIT_TAG