include:
  - component: gitlab.com/marcelotsvaz/gitlab/sane-workflow@main
  - component: gitlab.com/marcelotsvaz/gitlab/stages@main
  - component: gitlab.com/marcelotsvaz/gitlab/sast@main
  - component: gitlab.com/marcelotsvaz/gitlab/secret-detection@main


variables:
    PIP_ROOT_USER_ACTION: ignore  # Ignore pip warning when running as root.
    gitlabPypiUrl: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi


default:
    image: python:3.12.0-alpine3.18@sha256:a5d1738d6abbdff3e81c10b7f86923ebcb340ca536e21e8c5ee7d938d263dba1
    
    before_script:
      - apk add --no-cache git
      - pip install --no-cache-dir pdm
      - pdm install --plugins
    
    interruptible: true



# 
# Build stage.
#---------------------------------------------------------------------------------------------------
Python Package:
    # Build package using PDM.
    
    extends: .buildStage
    
    script:
      - pdm build
      
      # Get data for link in GitLab release.
      - cd .staging/dist/
      - printf 'wheelName=%s\n' *.whl >> ../package.env
      - echo wheelHash=$(sha256sum *.whl | cut -d ' ' -f 1 ) >> ../package.env
      - printf 'sdistName=%s\n' *.tar.gz >> ../package.env
      - echo sdistHash=$(sha256sum *.tar.gz | cut -d ' ' -f 1 ) >> ../package.env
    
    artifacts:
        name: package
        expose_as: Package distribution
        paths:
          - .staging/dist/
        
        reports:
            dotenv: .staging/package.env


Documentation:
    # Build documentation using MkDocs.
    
    extends: .buildStage
    
    variables:
        pagesPublicDir: .staging/pages
        index: index.html
    
    script:
      - apk add --no-cache gcc musl-dev zlib-dev jpeg-dev
      - pdm sync --no-default --group docs
      - pdm run docs
    
    rules:
      - if: $CI_PIPELINE_TYPE == 'merge_request'
        variables:
            useDirectoryUrls: 'false'
    
    artifacts:
        paths:
          - !reference [ Documentation, variables, pagesPublicDir ]



# 
# Test stage.
#---------------------------------------------------------------------------------------------------
Unit Tests:
    # Run unit tests on package.
    
    extends: .testStage
    
    script:
      - pdm sync --group dev
      - pdm test
    
    coverage: /^TOTAL.+?(\d+(?:\.\d+)?\%)$/
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: .staging/coverage.xml



# 
# Staging stage.
#---------------------------------------------------------------------------------------------------
Documentation Review App:
    # Deploy documentation as a job artifact and create a Review App for it.
    
    extends: .stagingStage
    
    needs: [ Documentation ]
    
    variables: !reference [ Documentation, variables ]
    
    environment:
        name: staging/${CI_COMMIT_REF_SLUG}/documentation
        url: https://${CI_PROJECT_NAMESPACE}.${CI_PAGES_DOMAIN}/-/${CI_PROJECT_NAME}/-/jobs/${CI_JOB_ID}/artifacts/${pagesPublicDir}/${index}
    
    artifacts: !reference [ Documentation, artifacts ]



# 
# Deploy stage.
#---------------------------------------------------------------------------------------------------
GitLab Package Registry:
    # Publish package to project's package registry.
    
    extends: .deployStage
    
    variables:
        PDM_PUBLISH_REPO: ${gitlabPypiUrl}
        PDM_PUBLISH_USERNAME: gitlab-ci-token
        PDM_PUBLISH_PASSWORD: ${CI_JOB_TOKEN}
    
    script:
      - pdm publish --no-build


PyPI:
    # Publish package to PyPI.
    
    extends: .deployStage
    
    variables:
        PDM_PUBLISH_USERNAME: __token__
        PDM_PUBLISH_PASSWORD: ${PYPI_API_TOKEN}
    
    script:
      - pdm publish --no-build


pages:
    # Deploy documentation to GitLab Pages.
    
    extends: .deployStage
    
    needs: [ Documentation ]
    
    environment:
        name: documentation
        url: ${CI_PAGES_URL}
    
    publish: !reference [ Documentation, variables, pagesPublicDir ] # No trailing slash.
    artifacts: !reference [ Documentation, artifacts ]



# 
# Release stage.
#---------------------------------------------------------------------------------------------------
GitLab Release:
    # Create GitLab release as last step in the pipeline.
    
    extends: .releaseStage
    
    image: registry.gitlab.com/gitlab-org/release-cli:latest@sha256:5a71acbadc47c1971100f5246b09f88ba09e84ebe7769e425475dce85245a2bf
    
    before_script: []
    
    release:
        tag_name: ${CI_COMMIT_TAG}
        description: ${CI_COMMIT_TAG}
        assets:
            links:
              - name: Documentation
                url: ${CI_PAGES_URL}
              
              - name: Package on PyPI
                url: https://pypi.org/project/marcelotsvaz-python-project-template/${CI_COMMIT_TAG}/
              
              - name: Wheel
                url: ${gitlabPypiUrl}/files/${wheelHash}/${wheelName}
                filepath: /${wheelName}
                link_type: package
              
              - name: Source Distribution
                url: ${gitlabPypiUrl}/files/${sdistHash}/${sdistName}
                filepath: /${sdistName}
                link_type: package